package media.tiger.tigerbox.ui.common;

import kotlin.Metadata;
import media.tiger.tigerbox.R;

/* compiled from: InfoDialogType.kt */
@Metadata(d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0000\n\u0002\u0018\u0002\n\u0002\b&\b\u0086\u0001\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u0001B\u000f\b\u0002\u0012\u0006\u0010\u0002\u001a\u00020\u0003¢\u0006\u0002\u0010\u0004R\u0011\u0010\u0002\u001a\u00020\u0003¢\u0006\b\n\u0000\u001a\u0004\b\u0005\u0010\u0006j\u0002\b\u0007j\u0002\b\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(¨\u0006)"}, d2 = {"Lmedia/tiger/tigerbox/ui/common/InfoDialogType;", "", "infoDialog", "Lmedia/tiger/tigerbox/ui/common/InfoDialog;", "(Ljava/lang/String;ILmedia/tiger/tigerbox/ui/common/InfoDialog;)V", "getInfoDialog", "()Lmedia/tiger/tigerbox/ui/common/InfoDialog;", "WRONG_PASSWORD", "WIFI_CONNECTION_FAILED", "INTERNET_CONNECTION_FAILED", "INTERNET_CONNECTION_FAILED_SINGLE_BUTTON", "ACCESS_FAILURE", "NFC_READ_ERROR", "CARD_NOT_FOUND", "WILDCARD_UNPROCESSED", "WILDCARD_PRIVATE", "EXPIRED_CARD", "ENTRY_BLOCKED", "GENERAL_ERROR", "PREMIUM_ACCESS_READY", "WILDCARD_ASSIGN_ERROR", "TIGERTICKET_403_ERROR", "TIGERTICKET_404_ERROR", "TIGERTICKET_410_ERROR", "TIGERTICKET_429_ERROR", "TIGERTICKET_REDEEM", "PARENTAL_GATE_WRONG_CUSTOM_PIN", "PARENTAL_GATE_WRONG_RANDOM_PIN", "DELETE_ALL_DOWNLOADS", "DELETE_PROFILE_DOWNLOADS", "DELETE_ALL_CONFIRMATION", "TIME_LIMIT_RESET_OR_ADJUST", "NO_WIRELESS_SIGNAL", "FIRST_SYNC_WARNING", "SECOND_SYNC_WARNING", "FINAL_SYNC_WARNING", "ERROR_SAFEGUARD_HARDWARE_900", "PRODUCT_LIST_ERROR", "SWIPE_INDICATOR_WIFI", "SWIPE_INDICATOR_GEAR", "FIRMWARE_ERROR", "app_tigerBoxRelease"}, k = 1, mv = {1, 6, 0}, xi = 48)
/* loaded from: classes4.dex */
public enum InfoDialogType {
    WRONG_PASSWORD(new InfoDialog(R.drawable.vector_error_700_wrong_password, R.string.error_700_headline, R.string.error_700_text, R.string.dialog_error_message_new_password_text, InfoDialogTypeResult.RETRY_PASSWORD, R.string.dialog_error_message_cancel_button_text, null, false, false, 0, false, 1984, null)),
    WIFI_CONNECTION_FAILED(new InfoDialog(R.drawable.vector_error_701_connection_with_a_new_wifi_failed, R.string.error_701_headline, R.string.error_701_text, R.string.dialog_error_message_try_again, InfoDialogTypeResult.RETRY_CONNECTION, R.string.dialog_error_message_cancel_button_text, null, false, false, 0, false, 1984, null)),
    INTERNET_CONNECTION_FAILED(new InfoDialog(R.drawable.vector_error_703_connection_with_internet_failed, R.string.error_703_headline, R.string.error_703_text, R.string.dialog_error_message_try_again, InfoDialogTypeResult.RETRY_CONNECTION, R.string.dialog_error_message_cancel_button_text, null, false, false, 0, false, 1984, null)),
    INTERNET_CONNECTION_FAILED_SINGLE_BUTTON(new InfoDialog(R.drawable.vector_error_703_connection_with_internet_failed, R.string.error_703_headline, R.string.error_703_text, R.string.dialog_error_message_ok_button_text, InfoDialogTypeResult.NO_INTERNET_ERROR, 0, null, false, false, 0, false, 2016, null)),
    ACCESS_FAILURE(new InfoDialog(R.drawable.vector_error_410_music_treble_clef, R.string.error_410_headline, R.string.error_410_text, R.string.dialog_error_message_ok_button_text, InfoDialogTypeResult.PRODUCT_ACQUISITION_ERROR, 0, null, false, false, 0, false, 2016, null)),
    NFC_READ_ERROR(new InfoDialog(R.drawable.error_dialog_nfc, R.string.error_nfc_card_read_title, R.string.error_nfc_card_read_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    CARD_NOT_FOUND(new InfoDialog(R.drawable.error_dialog_wildcard_invalid, R.string.error_wildcard_not_valid_title, R.string.error_wildcard_not_valid_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    WILDCARD_UNPROCESSED(new InfoDialog(R.drawable.error_dialog_wildcard_unprocessed, R.string.error_nfc_card_unprocessed_title, R.string.error_nfc_card_unprocessed_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    WILDCARD_PRIVATE(new InfoDialog(R.drawable.error_dialog_wildcard_private, R.string.error_nfc_card_private_title, R.string.error_nfc_card_private_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    EXPIRED_CARD(new InfoDialog(R.mipmap.ticket_warning, R.string.error_nfc_card_expired_title, R.string.error_nfc_card_expired_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    ENTRY_BLOCKED(new InfoDialog(R.drawable.vector_header_close, R.string.error_nfc_card_entry_blocked_title, R.plurals.error_nfc_card_entry_blocked_message, R.string.dialog_error_message_ok_button_text, null, -1, null, true, false, 0, false, 1280, null)),
    GENERAL_ERROR(new InfoDialog(R.drawable.vector_error, R.string.error_nfc_card_general_title, R.string.error_nfc_card_general_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    PREMIUM_ACCESS_READY(new InfoDialog(R.drawable.dialog_success_nfc_premium_access, -1, R.string.success_premium_access_nfc_card_message, R.string.success_premium_access_nfc_card_button, null, 0, null, false, false, 0, false, 2032, null)),
    WILDCARD_ASSIGN_ERROR(new InfoDialog(R.drawable.error_dialog_assign_wildcard, R.string.error_nfc_card_assign_title, R.string.error_nfc_card_assign_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    TIGERTICKET_403_ERROR(new InfoDialog(R.drawable.vector_error, R.string.error_nfc_tigerticket_403_title, R.string.error_nfc_tigerticket_403_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    TIGERTICKET_404_ERROR(new InfoDialog(R.drawable.vector_error, R.string.error_nfc_tigerticket_404_title, R.string.error_nfc_tigerticket_404_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    TIGERTICKET_410_ERROR(new InfoDialog(R.mipmap.ticket_warning, R.string.error_nfc_card_expired_title, R.string.error_nfc_card_expired_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    TIGERTICKET_429_ERROR(new InfoDialog(R.drawable.vector_error, R.string.error_nfc_tigerticket_429_title, R.string.error_nfc_tigerticket_429_message, R.string.dialog_error_message_ok_button_text, null, -1, null, true, false, 1, false, 1280, null)),
    TIGERTICKET_REDEEM(new InfoDialog(-1, R.string.nfc_tigerticket_redeem_confirmation_title, R.string.nfc_tigerticket_redeem_confirmation_message, R.string.nfc_tigerticket_redeem_right_text, InfoDialogTypeResult.TIGER_TICKET_REDEEM_CONFIRMED, R.string.nfc_tigerticket_redeem_left_text, InfoDialogTypeResult.TIGER_TICKET_REDEEM_CANCELED, true, false, 0, false, 1792, null)),
    PARENTAL_GATE_WRONG_CUSTOM_PIN(new InfoDialog(R.drawable.tigerbox_lock_closed_red, R.string.dialog_parental_gate_wrong_custom_pin_title, R.string.dialog_parental_gate_wrong_custom_pin_message, R.string.dialog_parental_gate_wrong_pin_button, null, -1, null, false, false, 0, false, 512, null)),
    PARENTAL_GATE_WRONG_RANDOM_PIN(new InfoDialog(R.drawable.tigerbox_lock_closed_red, R.string.dialog_parental_gate_wrong_random_pin_title, R.string.dialog_parental_gate_wrong_random_pin_message, R.string.dialog_parental_gate_wrong_pin_button, null, -1, null, false, false, 0, false, 512, null)),
    DELETE_ALL_DOWNLOADS(new InfoDialog(-1, R.string.dialog_delete_all_downloads_title, R.string.dialog_delete_all_downloads_message, R.string.dialog_delete_all_downloads_positive_button, InfoDialogTypeResult.DELETE_DOWNLOADS_CONFIRMED, R.string.dialog_error_message_cancel_button_text, null, false, false, 0, false, 1984, null)),
    DELETE_PROFILE_DOWNLOADS(new InfoDialog(-1, R.string.dialog_delete_profile_downloads_title, R.string.dialog_delete_profile_downloads_message, R.string.dialog_delete_profile_downloads_right_button, InfoDialogTypeResult.DELETE_DOWNLOADS_CONFIRMED, R.string.dialog_delete_profile_downloads_left_button, InfoDialogTypeResult.DELETE_PROFILE_DOWNLOADS_CONFIRMED, true, true, 0, false, 512, null)),
    DELETE_ALL_CONFIRMATION(new InfoDialog(-1, R.string.dialog_delete_all_downloads_confirmation_title, R.string.dialog_delete_all_downloads_confirmation_message, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null)),
    TIME_LIMIT_RESET_OR_ADJUST(new InfoDialog(-1, R.string.dialog_time_limit_reset_or_adjust_title, R.string.dialog_time_limit_reset_or_adjust_message, R.string.dialog_time_limit_adjust_button, InfoDialogTypeResult.TIME_LIMIT_ADJUST, R.string.dialog_time_limit_reset_button, InfoDialogTypeResult.TIME_LIMIT_RESET, false, false, 0, false, 1920, null)),
    NO_WIRELESS_SIGNAL(new InfoDialog(R.drawable.error_dialog_no_wifi_signal, R.string.error_no_wlan_signal_title, R.string.error_no_wlan_signal_message, R.string.error_no_wlan_signal_positive_button, InfoDialogTypeResult.SELECT_WIFI_NETWORKS, R.string.dialog_error_message_cancel_button_text, null, false, false, 0, false, 1984, null)),
    FIRST_SYNC_WARNING(new InfoDialog(R.drawable.error_dialog_sync_first_warning, R.string.error_offline_warning_title, R.string.error_offline_first_warning_message, R.string.error_offline_warning_positive_button, InfoDialogTypeResult.CONFIRM_SYNC, R.string.error_offline_warning_negative_button, null, false, false, 0, false, 1984, null)),
    SECOND_SYNC_WARNING(new InfoDialog(R.drawable.error_dialog_sync_second_warning, R.string.error_offline_warning_title, R.string.error_offline_second_warning_message, R.string.error_offline_warning_positive_button, InfoDialogTypeResult.CONFIRM_SYNC, R.string.error_offline_warning_negative_button, null, false, false, 0, false, 1984, null)),
    FINAL_SYNC_WARNING(new InfoDialog(R.drawable.error_dialog_sync_second_warning, R.string.error_offline_warning_title, R.string.error_offline_final_warning_message, R.string.error_offline_warning_positive_button, InfoDialogTypeResult.CONFIRM_SYNC_FINAL, R.string.error_offline_warning_negative_button, null, false, false, 0, false, 1984, null)),
    ERROR_SAFEGUARD_HARDWARE_900(new InfoDialog(R.drawable.error_900_hardware, R.string.error_900_headline, R.string.error_900_text, 0, null, 0, null, false, false, 0, false, 2040, null)),
    PRODUCT_LIST_ERROR(new InfoDialog(R.drawable.error_dialog_product_list_error, R.string.error_product_list_title, R.string.error_product_list_message, R.string.dialog_error_message_ok_button_text, InfoDialogTypeResult.PRODUCT_LIST_ERROR, 0, null, false, false, 0, false, 2016, null)),
    SWIPE_INDICATOR_WIFI(new InfoDialog(-2, R.string.open_parental_settings_dialog_title, R.string.open_parental_settings_dialog_text_wifi, R.string.ota_not_available_button, null, 0, null, false, false, 0, false, 2032, null)),
    SWIPE_INDICATOR_GEAR(new InfoDialog(-2, R.string.open_parental_settings_dialog_title, R.string.open_parental_settings_dialog_text_gear, R.string.ota_not_available_button, null, 0, null, false, false, 0, false, 2032, null)),
    FIRMWARE_ERROR(new InfoDialog(R.drawable.error_dialog_firmware, R.string.error_dialog_firmware_dialog_title, R.string.error_dialog_firmware_dialog_text, R.string.dialog_error_message_ok_button_text, null, 0, null, false, false, 0, false, 2032, null));
    
    private final InfoDialog infoDialog;

    InfoDialogType(InfoDialog infoDialog) {
        this.infoDialog = infoDialog;
    }

    public final InfoDialog getInfoDialog() {
        return this.infoDialog;
    }
}
